import { useLanguage } from "@/contexts/LanguageContext";
import { Shield, AlertTriangle, BookOpen, Bot, Camera } from "lucide-react";
import AppLayout from "@/components/AppLayout";

export default function Disclaimer() {
  const { lang } = useLanguage();

  const sections = lang === "fr" ? [
    {
      icon: Shield,
      title: "Avertissement Médical Général",
      content: `Les informations fournies par Plantinel — The Apothecary sont à titre informatif et éducatif uniquement. Elles ne constituent pas un avis médical, un diagnostic ou un traitement. Consultez toujours un professionnel de santé qualifié avant de commencer tout traitement à base de plantes, surtout si vous êtes enceinte, allaitez, prenez des médicaments ou avez des conditions médicales préexistantes.`,
    },
    {
      icon: BookOpen,
      title: "Connaissances Traditionnelles",
      content: `Le contenu relatif aux usages traditionnels des plantes est basé sur des pratiques historiques et culturelles. Ces informations sont présentées à des fins éducatives et ne doivent pas être interprétées comme des recommandations médicales. Les niveaux de preuve sont clairement indiqués pour chaque plante et remède.`,
    },
    {
      icon: Bot,
      title: "Contenu Généré par l'IA",
      content: `Certaines cartes et recommandations sont générées par intelligence artificielle. Bien que nous nous efforcions d'assurer l'exactitude, le contenu généré par l'IA peut contenir des erreurs ou des omissions. Vérifiez toujours les informations avec des sources fiables et consultez un professionnel de santé avant de suivre tout conseil.`,
    },
    {
      icon: Camera,
      title: "Identification par Photo",
      content: `L'identification des plantes par photo n'est pas fiable à 100%. Ne consommez jamais une plante uniquement sur la base d'une identification par image. Une identification incorrecte peut entraîner des conséquences graves pour la santé. Vérifiez toujours avec un botaniste ou un expert qualifié.`,
    },
    {
      icon: AlertTriangle,
      title: "Folklore et Vertus Mystiques",
      content: `Le contenu relatif au folklore, aux vertus mystiques et aux croyances traditionnelles est présenté à des fins culturelles et historiques uniquement. Ces informations n'ont pas été vérifiées scientifiquement et ne doivent pas servir de base à des décisions de santé. Elles reflètent des traditions culturelles et non des faits médicaux établis.`,
    },
  ] : [
    {
      icon: Shield,
      title: "General Medical Disclaimer",
      content: `The information provided by Plantinel — The Apothecary is for informational and educational purposes only. It does not constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional before starting any herbal treatment, especially if you are pregnant, breastfeeding, taking medications, or have pre-existing medical conditions.`,
    },
    {
      icon: BookOpen,
      title: "Traditional Knowledge",
      content: `Content related to traditional plant uses is based on historical and cultural practices. This information is presented for educational purposes and should not be interpreted as medical recommendations. Evidence levels are clearly indicated for each plant and remedy.`,
    },
    {
      icon: Bot,
      title: "AI-Generated Content",
      content: `Some cards and recommendations are generated by artificial intelligence. While we strive for accuracy, AI-generated content may contain errors or omissions. Always verify information with reliable sources and consult a healthcare professional before following any advice.`,
    },
    {
      icon: Camera,
      title: "Photo Identification",
      content: `Plant identification from photos is not 100% reliable. Never consume a plant based solely on image identification. Incorrect identification can lead to serious health consequences. Always verify with a qualified botanist or expert.`,
    },
    {
      icon: AlertTriangle,
      title: "Folklore & Mystical Virtues",
      content: `Content related to folklore, mystical virtues, and traditional beliefs is presented for cultural and historical purposes only. This information has not been scientifically verified and should not be used as a basis for health decisions. It reflects cultural traditions, not established medical facts.`,
    },
  ];

  return (
    <AppLayout>
      <div className="container py-8 max-w-3xl mx-auto px-4">
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-500/10 text-amber-700 text-sm font-medium mb-4">
            <AlertTriangle className="w-4 h-4" />
            {lang === "fr" ? "Avertissement Médical" : "Medical Disclaimer"}
          </div>
          <h1 className="font-serif text-3xl md:text-4xl font-bold text-foreground mb-3">
            {lang === "fr" ? "Avertissements et Conditions" : "Disclaimers & Terms"}
          </h1>
          <p className="text-muted-foreground max-w-xl mx-auto">
            {lang === "fr"
              ? "Veuillez lire attentivement ces avertissements avant d'utiliser Plantinel."
              : "Please read these disclaimers carefully before using Plantinel."}
          </p>
        </div>

        <div className="space-y-6">
          {sections.map((section, i) => (
            <div key={i} className="botanical-card p-6">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-xl bg-amber-500/10 flex items-center justify-center shrink-0">
                  <section.icon className="w-5 h-5 text-amber-600" />
                </div>
                <div>
                  <h2 className="font-serif text-lg font-semibold text-foreground mb-2">{section.title}</h2>
                  <p className="text-sm text-foreground/80 leading-relaxed">{section.content}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-10 p-6 rounded-xl bg-destructive/5 border border-destructive/10 text-center">
          <AlertTriangle className="w-8 h-8 text-destructive mx-auto mb-3" />
          <p className="text-sm font-medium text-destructive mb-1">
            {lang === "fr" ? "En cas d'urgence médicale" : "In case of medical emergency"}
          </p>
          <p className="text-sm text-foreground/70">
            {lang === "fr"
              ? "Appelez immédiatement les services d'urgence de votre pays. Ne vous fiez jamais à cette application pour des situations d'urgence."
              : "Call your local emergency services immediately. Never rely on this application for emergency situations."}
          </p>
        </div>
      </div>
    </AppLayout>
  );
}
