export const jobs = [
  {
    id: "BK-1042",
    column: "New",
    urgency: "Emergency",
    waiting: "2h waiting",
    title: "Kitchen pipe leaking under the sink",
    commune: "Cocody",
    service: "Plumbing",
    assignment: "Unassigned",
    action: "Assign ->",
    customer: "Aminata K.",
    phone: "+225 07 89 12 34 56",
    location: "Cocody, Abidjan",
    status: "Unassigned",
    created: "Today, 8:45 AM (2h ago)",
    description: "Water is leaking continuously from the pipe under the kitchen sink.",
    attachments: "2 photos"
  },
  {
    id: "BK-1041",
    column: "New",
    urgency: "Today",
    waiting: "",
    title: "Office AC not cooling in meeting room",
    commune: "Plateau",
    service: "Air conditioning",
    assignment: "Unassigned",
    action: "Assign ->",
    customer: "Residence Plateau",
    phone: "+225 07 65 40 22 18",
    location: "Plateau, Abidjan",
    status: "Unassigned",
    created: "Today, 9:25 AM",
    description: "The meeting room AC is running, but the room stays warm.",
    attachments: "1 photo"
  },
  {
    id: "BK-1039",
    column: "Contacted",
    urgency: "Today",
    waiting: "5h waiting",
    title: "Breaker trips every night",
    commune: "Marcory",
    service: "Electrical",
    assignment: "Assigned to Awa Traore",
    action: "Open ->",
    customer: "Kone M.",
    phone: "+225 05 44 33 12 09",
    location: "Marcory, Abidjan",
    status: "Contacted",
    created: "Today, 6:10 AM",
    description: "Main breaker trips repeatedly after evening appliance use.",
    attachments: "No attachments"
  },
  {
    id: "BK-1036",
    column: "Quoted",
    urgency: "Today",
    waiting: "",
    title: "Bedroom wardrobe doors need repair",
    commune: "Cocody",
    service: "Carpentry",
    assignment: "Quoted • 450,000 FCFA",
    action: "View quote ->",
    customer: "Hotel Cocody",
    phone: "+225 01 90 43 22 00",
    location: "Cocody, Abidjan",
    status: "Quoted",
    created: "Yesterday, 4:35 PM",
    description: "Three bedroom wardrobe doors need hinge and alignment repair.",
    attachments: "4 photos"
  },
  {
    id: "BK-1034",
    column: "Scheduled",
    urgency: "Scheduled",
    waiting: "",
    title: "Post-renovation cleaning",
    commune: "Plateau",
    service: "Cleaning",
    assignment: "Today, 2:00 PM",
    secondaryAssignment: "Assigned to Nadia Konan",
    action: "Open ->",
    customer: "Nadia S.",
    phone: "+225 07 33 80 19 40",
    location: "Plateau, Abidjan",
    status: "Scheduled",
    created: "Yesterday, 12:20 PM",
    description: "Small office needs full cleaning after renovation work.",
    attachments: "3 photos"
  },
  {
    id: "BK-1031",
    column: "In progress",
    urgency: "In progress",
    waiting: "3h",
    title: "AC not cooling",
    commune: "Cocody",
    service: "Air conditioning",
    assignment: "Assigned to Koffi N.",
    action: "Open ->",
    customer: "Yao Family",
    phone: "+225 07 21 63 55 19",
    location: "Cocody, Abidjan",
    status: "In progress",
    created: "Today, 7:50 AM",
    description: "Living room AC is blowing warm air after a power cut.",
    attachments: "1 photo"
  }
];

export const columns = [
  { name: "New", alert: "4 unassigned" },
  { name: "Contacted", alert: "Oldest: 2h" },
  { name: "Quoted", alert: "1 waiting" },
  { name: "Scheduled", alert: "Today" },
  { name: "In progress", alert: "1 delayed" }
];

export const kpis = [
  { label: "Open jobs", value: "16" },
  { label: "Unassigned jobs", value: "7" },
  { label: "Jobs stuck > 24h", value: "3" },
  { label: "Match rate", value: "67%" },
  { label: "Artisans active", value: "24 / 35" }
];
